name: firebase-test-when-pr-created

on:
  pull_request:
    branches: 
      - master
      - dev
    paths:
      - 'apollo/**'
      - '.github/workflows/firebase_test_pr.yml'
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter the name of this workflow trigger'
        required: true

jobs:
  firebase-emulator-test:
    runs-on: ubuntu-latest

    steps:
    - name: Into the repo
      uses: actions/checkout@v2
    - name: Setup node environment
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install necessary npm packages in the functions 
      run: npm ci
      working-directory: ./apollo
    - name: Install firebase CLI
      run: npm install -g firebase-tools
      # https://firebase.google.com/docs/cli#cli-ci-systems
    - name: run test
      # jest would not exit after the test.
      # workaround: `--forceExit`, https://github.com/facebook/jest/issues/7287#issuecomment-511217501
      # https://github.com/firebase/firebase-js-sdk/issues/4884
      # https://github.com/facebook/jest/issues/11464#issuecomment-850055381
      run: firebase emulators:exec "npx jest --ci --forceExit"  --only firestore,auth 
      working-directory: ./apollo
    